Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/SymbolArray:
  Enabled: true
  Exclude:
    - db/migrate/*

AllCops:
  Exclude:
    - db/schema.rb
